apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: zanthus-ecosistema-sonarqube
  description: SonarQube analysis for Zanthus Ecosistema
  annotations:
    sonarcloud.io/project-key: zanthus-ecosistema
spec:
  type: code-quality
  owner: vladimir.ribeiro@zanthus.com.br
  dependsOn:
    - component:default/zanthus-ecosistema
  links:
    - title: SonarQube Dashboard
      url: https://your-sonarqube-url/dashboard?id=zanthus-ecosistema
